### ISSUE TITLE
Populate from preset doesn't work in MMS activity

### ISSUE THREAD

**Issue by samarthd** [samarthd/FutureMessengerApp#46]
It is likely due to the fact that MMS activity overrides onActivityForResult() which means it doesn't respond to the stuff EditTextMessageActivity is waiting for. It's possible that calling super.onActivityForResult() in the override could fix the problem. Probably set that as the default case, because we don't want the super method's cases to be triggered and then drop to our activity and do _another_ thing. We should check our cases first, then call super.onActivityForResult().

**Comment by xtkbilly** [comment]
This should be fixed already, and on dev. Needs to be checked, however.
